#!/bin/bash
#Related regexes for making this type of file:
#1. find "^" and replace with "count=\$\(\(\$count\+\$\(egrep -io '\\b"
#2. find "$" and replace with "\\b' "\$f" \| wc -w\)\)\)"

# Count the # of death word tokens
for f in /home/mulhollandm2/Project2/by_song/lemmatized/non-suicide/*.txt
do

count=0
count=$(($count+$(egrep -io '\basphyxia\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\baway\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bbe\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bbereave\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bbook\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bbreak\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bbreath\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bbucket\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bcareer\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bcease\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bclose\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bcoil\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bdead\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bdeadly\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bdecay\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bdefunct\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bdemise\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bdemised\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bdeparture\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bdie\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bdisease\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bdissolution\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bdoom\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bdoornail\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bdoorpost\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bdrop\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bdust\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bebb\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bend\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\beternity\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\beuthanasia\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bexanimate\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bexpire\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bextinct\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bextinction\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bfail\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bfall\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bgasp\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bgive\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bgrave\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bhand\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bhang\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bherring\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bhippocratic\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\binanimate\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bjaw\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bkick\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\blamentation\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\blate\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\blie\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\blifeless\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bloss\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bmorbidity\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bmore\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bmoribund\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bmorient\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bmortal\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bmortality\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bmortis\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bmortuary\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bnatural\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bnecrology\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bno\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bobit\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bobituary\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bpass\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bpay\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bperish\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bpop\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bquietus\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\brattle\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\brelinquish\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bresign\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\brest\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\brun\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bseal\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bshade\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bsink\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bsleep\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bsong\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bstillborn\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bsuffocation\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bsurrender\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\btake\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bterror\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bturn\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\buntimel\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\buntimely\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bvalley\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bviolent\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bwarrant\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bwatch\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\byield\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bagony\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bday\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bdeath\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bdecease\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bdepart\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bdying\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bgo\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\blast\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\brelease\b' "$f" | wc -w)))
echo $count

done > /home/mulhollandm2/Project2/by_song/lemmatized/non-suicide/deathWord_TokenCount.csv

# List of files in order of access
for f in /home/mulhollandm2/Project2/by_song/lemmatized/non-suicide/*.txt
do

echo "$f"

done > /home/mulhollandm2/Project2/by_song/lemmatized/non-suicide/fileList.csv
