#!/bin/bash
#Related regexes for making this type of file:
#1. find "^" and replace with "count=\$\(\(\$count\+\$\(egrep -io '\\b"
#2. find "$" and replace with "\\b' "\$f" \| wc -w\)\)\)"

# Count the # of drug word tokens
for f in /home/mulhollandm2/Project2/by_song/lemmatized/non-suicide/*.txt
do

count=0
count=$(($count+$(egrep -io '\babuse\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bacid\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\baddict\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\baddiction\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bagent\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\baid\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\balcohol\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\balcoholic\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\balkie\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\balky\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\balleviation\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\balter\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bamphetamine\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bantidote\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bassistance\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bbad\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bban\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bbiologic\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bblow\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bbooze\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bbust\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bcannabis\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bcatholicon\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bcharge\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bchemical\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bcigarette\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bcocaine\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bcoke\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bcommmon\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bcomplication\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bcondemn\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bcool\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bcorrective\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bcounteractant\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bcounteragent\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bcountermeasure\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bcriminal\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bcure\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bdepend\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bdepressant\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bdisorder\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bdope\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bdose\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bdrink\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\becstasy\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\beffective\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bemotion\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\benjoy\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bessence\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bessential\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bexpensive\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bgood\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bhallucinogenic\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bhappiness\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bharm\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bhashish\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bhealth\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bhell\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bhelp\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bheroin\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bhigh\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bhook\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\billegal\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bimportant\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bingest\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\binject\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bintend\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bintoxicate\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bjab\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bjay\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bjoint\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bjunk\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bjunkie\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bjunky\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bkef\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bkif\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\blabel\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bliquor\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bload\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\blsd\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bmake\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bmedical\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bmedicament\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bmedicant\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bmedication\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bmedicinal\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bmedicine\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bmerry\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bmetabolize\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bmethamphetamine\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bmind\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bmule\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bnark\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bnecessary\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bnice\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bnostrum\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bobsess\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\boffence\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bofficer\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bopiate\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bout\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\boverdose\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bpanacea\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bpass\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bpatient\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bpharmaceutic\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bpharmaceutical\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bpharmacon\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bphysic\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bpill\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bpiss\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bplacebo\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bpoison\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bpotent\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bpotion\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bprescribe\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bprescription\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bprolong\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bproprietary\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bpsychological\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bquick\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\brecovery\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\brecreation\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bredress\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\brehab\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bremedy\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\breparation\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\brestora\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\brip\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bsedative\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bserious\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bshitfaced\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bsleep\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bsmoke\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bspeed\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bstimulant\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bstupid\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bsubstance\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bsuppression\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bsyringe\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\btear\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\btherapeutic\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\btight\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\btipsy\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\btive\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\btrash\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\btreat\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\btreatment\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bunconscious\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bunder\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bupper\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\buse\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\buser\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bvarious\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bvino\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bvitae\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bwagon\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bwaste\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bwee\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bwell\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bwhack\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bwine\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bwreck\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bdevelop\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bdrug\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\belixir\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bheal\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\binfluence\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bmarijuana\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bmickey\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bnarcotic\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\btonic\b' "$f" | wc -w)))
count=$(($count+$(egrep -io '\bfix\b' "$f" | wc -w)))
echo $count

done > /home/mulhollandm2/Project2/by_song/lemmatized/non-suicide/drugWord_TokenCount.csv

# List of files in order of access
for f in /home/mulhollandm2/Project2/by_song/lemmatized/non-suicide/*.txt
do

echo "$f"

done > /home/mulhollandm2/Project2/by_song/lemmatized/non-suicide/fileList.csv
